import { Howl, Howler } from "howler";

export class AudioManager {
  private sounds = new Map<string, Howl>();
  private audioSprite: Howl;

  constructor() {
    Howler.volume(1);
  }

  // Spritemap generated by audiosprite.
  loadSpritemap = (spriteMap: any) => {
    if (spriteMap == undefined) {
      return;
    }
    this.audioSprite = new Howl({
      ...spriteMap,
      preload: true,
    });
  };

  // loadSounds = (soundMap: Record<string, string>) => {
  //   for (const [name, src] of Object.entries(soundMap)) {
  //     this.loadSound(name, src);
  //   }
  // };

  // loadSound = (name: string, src: string) => {
  //   this.sounds.set(
  //     name,
  //     new Howl({
  //       src: [src],
  //       preload: true,
  //     })
  //   );
  // };

  isPlaying = (nameOrId) => {
    return this.audioSprite.playing(nameOrId);
  };

  updateSoundLoopValue = (nameOrId, status) => {
    if (!this.audioSprite || !nameOrId) {
      return;
    }

    this.audioSprite.loop(status, nameOrId);
  };

  playSound = (nameOrId) => {
    if (!this.audioSprite) {
      return;
    }
    // @ts-expect-error
    return this.audioSprite.play(nameOrId);
  };

  pauseSound = (nameOrId) => {
    if (!this.audioSprite) {
      return;
    }

    this.audioSprite.pause(nameOrId);
  };

  stopSound = (nameOrId) => {
    if (!this.audioSprite) {
      return;
    }
    // @ts-expect-error
    this.audioSprite.stop(nameOrId);
  };

  // getSound = (name: string) => {
  //   return this.sounds.get(name);
  // };

  // playSound = (name: string, spriteId?: number) => {
  //   const sound = this.sounds.get(name);
  //   if (!sound) {
  //     return;
  //   }
  //   // @ts-expect-error
  //   return sound.play(spriteId);
  // };

  // pauseSound = (name: string, spriteId?: number) => {
  //   const sound = this.sounds.get(name);
  //   if (!sound) {
  //     return;
  //   }

  //   // @ts-expect-error
  //   sound.pause(spriteId);
  // };

  // stopSound = (name: string, spriteId?: number) => {
  //   const sound = this.sounds.get(name);
  //   if (!sound) {
  //     return;
  //   }
  //   // @ts-expect-error
  //   sound.stop(spriteId);
  // };

  // TODO: Set Volume
}
